CREATE TABLE IF NOT EXISTS HELP_REQUESTS(
    ID BIGSERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR,
    RESPONSE VARCHAR,
    REQUESTER_ID integer NOT NULL,
    STATUS VARCHAR(255),
    date timestamp NOT NULL
);