CREATE TABLE IF NOT EXISTS ALERTS(
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(400),
    DESCRIPTION VARCHAR(1000),
    date timestamp NOT NULL,
    PRIORITY integer NOT NULL,
    TYPE VARCHAR(255),
    STYLE VARCHAR(255),
    SEEN boolean,
    USER_ID integer NOT NULL
);